version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bcc_canteen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anjaycoding
      MYSQL_DATABASE: bcc_canteen
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
